function compile_edge_face_correspondence

    mex -v -O edge_face_correspondence.cpp ...
        CXXOPTIMFLAGS="-O3" ...
        CXXFLAGS="$CXXFLAGS -std=c++17" ...
        -I/usr/include:/usr/local/include ...
        -L/usr/lib:/usr/local/lib -lCGAL -lgmp -lboost_thread

end

