function compile_minimize_elastic_energy

    % mex -v -O minimize_elastic_energy.cpp ...
    %     -I/usr/include:/usr/local/include ...
    %     -L/usr/lib:/usr/local/lib -lCGAL -lgmp -lboost_thread
    
    mex -v -O minimize_elastic_energy.cpp ...
        CXXOPTIMFLAGS="-O3" ...
        CXXFLAGS="$CXXFLAGS -std=c++17" ...
        -I/usr/include:/usr/local/include ...
        -I/usr/local/include/libigl/include ...
        -L/usr/lib:/usr/local/lib -lCGAL -lgmp -lboost_thread

end

